version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback 
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
            name: "build image and push to docker hub"
            command: |
                cp Dockerfile.production Dockerfile
                docker build -t thingsanalytic/example-nodejs-express:latest .
                docker build -t thingsanalytic/example-nodejs-express:${CIRCLE_SHA1} .
                docker push thingsanalytic/example-nodejs-express:latest
                docker push thingsanalytic/example-nodejs-express:${CIRCLE_SHA1}
      - run: echo Done
